config/routes.rb
Rails.application.routes.draw do
  resources :pets
  resources :teachers
  resources :students
  get 'home' => 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :age, :breed)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :interests, :grade, :avatar)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :age, :interests)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Classroom</title>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Raleway" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
      <%= link_to "Classroom", root_path, class: "navbar-brand" %>      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Students', students_path %></li>
          <li><%= link_to 'Teachers', teachers_path %></li>
          <li><%= link_to 'Pets', pets_path %></li>  
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="navbar-fixed-bottom text-center">
    <p>&copy;2016, Derek Scace</p>
  </footer>
</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(pet) do |f| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.number_field :age, class: "form-control", placeholder: "Age" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_field :breed, class: "form-control", placeholder: "Breed" %>
    </div>
  </div>

  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success alert-dismissable" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </p>
<% end %>

<h1>Pets</h1>

<div class="row">
<div class="col-md-4 col-md-offset-4 text-center">
<%= link_to 'New Pet', new_pet_path, class: "btn btn-info" %>
</div>
</div> 

<br>



<div class="row">
  <% @pets.each do |pet| %>
    <div class="col-md-3" id="lil_div">
      <div class="well">
        <h2><%= "#{pet.name}" %></h2>
        <p>Age: <%= pet.age %></p>
        <p>Breed: <%= pet.breed %></p>
        <p><%= link_to 'Show', pet, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_pet_path(pet), class: "btn btn-warning" %>
        <%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success alert-dismissable" role="alert">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pet.breed %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.number_field :age, class: "form-control", placeholder: "Age" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_field :interests, class: "form-control", placeholder: "Interests" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success alert-dismissable" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </p>
<% end %>


<h1>Students</h1>

<div class="row">
<div class="col-md-4 col-md-offset-4 text-center">
<%= link_to 'New Student', new_student_path, class: "btn btn-info" %>
</div>
</div> 

<br>

<div class="row">
  <% @students.each do |student| %>
    <div class="col-md-3">
      <div class="well">
        <% if student.avatar_file_name != nil %>
          <%= image_tag student.avatar.url(:medium), class: "img-responsive" %>
        <% end %>
        <h2><%= "#{student.name}" %></h2>
        <p>Age: <%= student.age %></p>
        <p>Interests: <%= student.interests %></p>
        <p><%= link_to 'Show', student, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_student_path(student), class: "btn btn-warning" %>
        <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success alert-dismissable" role="alert">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </p>
<% end %>

<% if @student.avatar_file_name != nil %>
	<%= image_tag @student.avatar.url(:medium), style: "padding-top: 15px" %>
<% end %>
<h2><%= "#{@student.name}" %></h2>
<p>Age: <%= @student.age %></p>
<p>Interests: <%= @student.interests %></p>

<div class="actions form-group">
	<%= link_to 'Edit', edit_student_path(@student), class: "btn btn-danger" %>
	<%= link_to 'Back', students_path, class: "btn btn-info" %>
</div>

app/views/teachers/_form.html.erb
<%= form_for(teacher) do |f| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.number_field :age, class: "form-control", placeholder: "Age" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_field :interests, class: "form-control", placeholder: "Interests" %>
    </div>
  </div>

  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success alert-dismissable" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </p>
<% end %>

<h1>Teachers</h1>

<div class="row">
<div class="col-md-4 col-md-offset-4 text-center">
<%= link_to 'New Teacher', new_teacher_path, class: "btn btn-info" %>
</div>
</div> 

<br>



<div class="row">
  <% @teachers.each do |teacher| %>
    <div class="col-md-3" id="lil_div">
      <div class="well">
        <h2><%= "#{teacher.name}" %></h2>
        <p>Age: <%= teacher.age %></p>
        <p>Interests: <%= teacher.interests %></p>
        <p><%= link_to 'Show', teacher, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_teacher_path(teacher), class: "btn btn-warning" %>
        <%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success alert-dismissable" role="alert">
  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= notice %>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @teacher.age %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @teacher.interests %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/welcome/index.html.erb
<div class="jumbotron" id="welcome">
		<h1>Welcome to the Classroom!</h1> 
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> 
</div>